"""remove_is_blacklisted

Revision ID: 0664830fbe2b
Revises: e7bb75995841
Create Date: 2026-01-31 15:14:12.085142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0664830fbe2b'
down_revision: Union[str, None] = 'e7bb75995841'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_blacklisted')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_blacklisted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
