"""added_is_custom_broadcast_and_custom_message_fields

Revision ID: 7298d039e346
Revises: 0664830fbe2b
Create Date: 2026-02-01 00:29:34.956587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7298d039e346'
down_revision: Union[str, None] = '0664830fbe2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trading_sessions', sa.Column('is_custom_broadcast', sa.Boolean(), nullable=True))
    op.add_column('trading_sessions', sa.Column('custom_message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trading_sessions', 'custom_message')
    op.drop_column('trading_sessions', 'is_custom_broadcast')
    # ### end Alembic commands ###
