"""Add target rate

Revision ID: 89b8e1a0b83f
Revises: 28fa7f4ec8d1
Create Date: 2026-02-10 22:27:35.394332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89b8e1a0b83f'
down_revision: Union[str, None] = '28fa7f4ec8d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trading_sessions', sa.Column('target_rate', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trading_sessions', 'target_rate')
    # ### end Alembic commands ###
