"""remove_session_status_and_order_table

Revision ID: e7bb75995841
Revises: 8fa33178f60f
Create Date: 2026-01-28 21:57:36.651980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e7bb75995841'
down_revision: Union[str, None] = '8fa33178f60f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_column('trading_sessions', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trading_sessions', sa.Column('status', postgresql.ENUM('CREATED', 'ACTIVE', 'COMPLETED', 'EXPIRED', name='sessionstatus'), autoincrement=False, nullable=True))
    op.create_table('orders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('side', postgresql.ENUM('BUY', 'SELL', name='tradedirection'), autoincrement=False, nullable=False),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'ACCEPTED', 'REJECTED', 'EXPIRED', name='orderstatus'), autoincrement=False, nullable=True),
    sa.Column('message_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('raw_message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('orders_group_id_fkey')),
    sa.ForeignKeyConstraint(['session_id'], ['trading_sessions.id'], name=op.f('orders_session_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], name=op.f('orders_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('orders_pkey'))
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    # ### end Alembic commands ###
